/// The frozen sas-pairing native ABI v1 surface as Dart sees it (P7-D-013, P8-D-001).
///
/// Private to the package. Every value here comes from the generated bindings, which are
/// generated from `core/include/sas_pairing.h`; the tables name each frozen value once so that
/// tests can compare them with `docs/p7-native-abi/abi-v1-manifest.md` row by row. No value is
/// reinterpreted: statuses are raw `int32_t` values, never trust verdicts, and handles stay
/// opaque 64-bit integers.
library;

import 'generated/sas_pairing_bindings.g.dart' as raw;

/// The only native ABI version this package binds. Deliberately a literal, not the header
/// macro: a header that changed its version must fail the tests, not be accepted silently.
const int requiredAbiVersion = 1;

/// The pointer width (bytes) of the only supported native target. The frozen record layouts
/// are 64-bit layouts; the loader refuses any other process before opening a library.
const int supportedPointerSize = 8;

/// The 25 frozen exports, in manifest order. The one Dart list of them: the loader's symbol
/// preflight, the tests, and the ffigen function filter (checked equal by tests) all use it.
const List<String> abiV1Exports = <String>[
  'sas_pairing_abi_version',
  'sas_pairing_runtime_create',
  'sas_pairing_runtime_destroy',
  'sas_pairing_authority_register',
  'sas_pairing_authority_release',
  'sas_pairing_authority_status',
  'sas_pairing_host_create',
  'sas_pairing_host_destroy',
  'sas_pairing_host_attach_windows_listener',
  'sas_pairing_host_detach_listener',
  'sas_pairing_host_drive',
  'sas_pairing_host_recheck_after_resume',
  'sas_pairing_connection_close',
  'sas_pairing_result_info',
  'sas_pairing_result_copy',
  'sas_pairing_result_destroy',
  'sas_pairing_connection_start_initiator',
  'sas_pairing_run_authorize_exposure',
  'sas_pairing_run_expose_key',
  'sas_pairing_run_presentation',
  'sas_pairing_run_approve_sas',
  'sas_pairing_run_emit_bootstrap_mac',
  'sas_pairing_run_reject_sas',
  'sas_pairing_run_cancel_sas',
  'sas_pairing_run_emit_initiator_finish',
];

/// Manifest §1.
const Map<String, int> abiV1Version = <String, int>{
  'SAS_PAIRING_ABI_VERSION': raw.SAS_PAIRING_ABI_VERSION,
  'SAS_PAIRING_ABI_VERSION_INVALID': raw.SAS_PAIRING_ABI_VERSION_INVALID,
};

/// Manifest §3: the 48 `sas_pairing_status_t` values. Every non-zero value, known or not, is a
/// failure; none is a trust verdict.
const Map<String, int> abiV1Statuses = <String, int>{
  'SAS_PAIRING_OK': raw.SAS_PAIRING_OK,
  'SAS_PAIRING_INVALID_ARGUMENT': raw.SAS_PAIRING_INVALID_ARGUMENT,
  'SAS_PAIRING_INVALID_HANDLE': raw.SAS_PAIRING_INVALID_HANDLE,
  'SAS_PAIRING_ALREADY_INITIALIZED': raw.SAS_PAIRING_ALREADY_INITIALIZED,
  'SAS_PAIRING_HANDLES_EXHAUSTED': raw.SAS_PAIRING_HANDLES_EXHAUSTED,
  'SAS_PAIRING_INVALID_SCOPE': raw.SAS_PAIRING_INVALID_SCOPE,
  'SAS_PAIRING_ALREADY_REGISTERED': raw.SAS_PAIRING_ALREADY_REGISTERED,
  'SAS_PAIRING_OWNERSHIP_UNAVAILABLE': raw.SAS_PAIRING_OWNERSHIP_UNAVAILABLE,
  'SAS_PAIRING_UNSUPPORTED_PLATFORM': raw.SAS_PAIRING_UNSUPPORTED_PLATFORM,
  'SAS_PAIRING_OWNERSHIP_UNCERTAIN': raw.SAS_PAIRING_OWNERSHIP_UNCERTAIN,
  'SAS_PAIRING_BUSY': raw.SAS_PAIRING_BUSY,
  'SAS_PAIRING_EXHAUSTED': raw.SAS_PAIRING_EXHAUSTED,
  'SAS_PAIRING_RESOURCE_LIMITED': raw.SAS_PAIRING_RESOURCE_LIMITED,
  'SAS_PAIRING_MISSING_AUTHORIZATION': raw.SAS_PAIRING_MISSING_AUTHORIZATION,
  'SAS_PAIRING_STALE_AUTHORIZATION': raw.SAS_PAIRING_STALE_AUTHORIZATION,
  'SAS_PAIRING_TERMINATED': raw.SAS_PAIRING_TERMINATED,
  'SAS_PAIRING_INVALID_BOOTSTRAP': raw.SAS_PAIRING_INVALID_BOOTSTRAP,
  'SAS_PAIRING_RUN_ENDED': raw.SAS_PAIRING_RUN_ENDED,
  'SAS_PAIRING_WRITE_PENDING': raw.SAS_PAIRING_WRITE_PENDING,
  'SAS_PAIRING_CEREMONY_INVALID_STATE': raw.SAS_PAIRING_CEREMONY_INVALID_STATE,
  'SAS_PAIRING_NO_LIVE_SAS': raw.SAS_PAIRING_NO_LIVE_SAS,
  'SAS_PAIRING_CEREMONY_IDENTITY_MISMATCH':
      raw.SAS_PAIRING_CEREMONY_IDENTITY_MISMATCH,
  'SAS_PAIRING_NOT_LOCALLY_APPROVED': raw.SAS_PAIRING_NOT_LOCALLY_APPROVED,
  'SAS_PAIRING_UNEXPECTED_SENDER_ROLE': raw.SAS_PAIRING_UNEXPECTED_SENDER_ROLE,
  'SAS_PAIRING_INVALID_REQUEST_ID': raw.SAS_PAIRING_INVALID_REQUEST_ID,
  'SAS_PAIRING_REQUEST_ID_GENERATION_FAILED':
      raw.SAS_PAIRING_REQUEST_ID_GENERATION_FAILED,
  'SAS_PAIRING_REQUEST_ID_MISMATCH': raw.SAS_PAIRING_REQUEST_ID_MISMATCH,
  'SAS_PAIRING_SHARED_CONTEXT_MISMATCH':
      raw.SAS_PAIRING_SHARED_CONTEXT_MISMATCH,
  'SAS_PAIRING_EXPECTED_PEER_MISMATCH': raw.SAS_PAIRING_EXPECTED_PEER_MISMATCH,
  'SAS_PAIRING_APPROVALS_NOT_AUTHENTICATED':
      raw.SAS_PAIRING_APPROVALS_NOT_AUTHENTICATED,
  'SAS_PAIRING_NOT_INITIATOR': raw.SAS_PAIRING_NOT_INITIATOR,
  'SAS_PAIRING_TRANSCRIPT_MISMATCH': raw.SAS_PAIRING_TRANSCRIPT_MISMATCH,
  'SAS_PAIRING_COMPLETED': raw.SAS_PAIRING_COMPLETED,
  'SAS_PAIRING_NO_PENDING_FINAL_ACK': raw.SAS_PAIRING_NO_PENDING_FINAL_ACK,
  'SAS_PAIRING_FINAL_ACK_MISMATCH': raw.SAS_PAIRING_FINAL_ACK_MISMATCH,
  'SAS_PAIRING_CEREMONY_TIMED_OUT': raw.SAS_PAIRING_CEREMONY_TIMED_OUT,
  'SAS_PAIRING_CEREMONY_CLOCK_UNAVAILABLE':
      raw.SAS_PAIRING_CEREMONY_CLOCK_UNAVAILABLE,
  'SAS_PAIRING_PENDING_EXPIRED': raw.SAS_PAIRING_PENDING_EXPIRED,
  'SAS_PAIRING_CEREMONY_CODEC_ERROR': raw.SAS_PAIRING_CEREMONY_CODEC_ERROR,
  'SAS_PAIRING_CEREMONY_CRYPTO_ERROR': raw.SAS_PAIRING_CEREMONY_CRYPTO_ERROR,
  'SAS_PAIRING_BUFFER_TOO_SMALL': raw.SAS_PAIRING_BUFFER_TOO_SMALL,
  'SAS_PAIRING_LISTENER_ALREADY_ATTACHED':
      raw.SAS_PAIRING_LISTENER_ALREADY_ATTACHED,
  'SAS_PAIRING_LISTENER_SETUP_FAILED': raw.SAS_PAIRING_LISTENER_SETUP_FAILED,
  'SAS_PAIRING_LISTENER_NOT_ATTACHED': raw.SAS_PAIRING_LISTENER_NOT_ATTACHED,
  'SAS_PAIRING_OWNER_LOOP_CLOSED': raw.SAS_PAIRING_OWNER_LOOP_CLOSED,
  'SAS_PAIRING_NETWORK_POLL_FAILED': raw.SAS_PAIRING_NETWORK_POLL_FAILED,
  'SAS_PAIRING_CONNECTION_ENDED': raw.SAS_PAIRING_CONNECTION_ENDED,
  'SAS_PAIRING_FATAL': raw.SAS_PAIRING_FATAL,
};

/// Manifest §4: the 84 values of the thirteen `uint32_t` namespaces (enumerations and flags).
const Map<String, int> abiV1Namespaces = <String, int>{
  'SAS_PAIRING_AUTHORITY_STATE_INVALID':
      raw.SAS_PAIRING_AUTHORITY_STATE_INVALID,
  'SAS_PAIRING_AUTHORITY_READY': raw.SAS_PAIRING_AUTHORITY_READY,
  'SAS_PAIRING_AUTHORITY_BUSY': raw.SAS_PAIRING_AUTHORITY_BUSY,
  'SAS_PAIRING_AUTHORITY_EXHAUSTED': raw.SAS_PAIRING_AUTHORITY_EXHAUSTED,
  'SAS_PAIRING_EVENT_INVALID': raw.SAS_PAIRING_EVENT_INVALID,
  'SAS_PAIRING_EVENT_CONNECTION_ACCEPTED':
      raw.SAS_PAIRING_EVENT_CONNECTION_ACCEPTED,
  'SAS_PAIRING_EVENT_ACCEPT_REFUSED': raw.SAS_PAIRING_EVENT_ACCEPT_REFUSED,
  'SAS_PAIRING_EVENT_LISTENER_DISABLED':
      raw.SAS_PAIRING_EVENT_LISTENER_DISABLED,
  'SAS_PAIRING_EVENT_CONNECTION_STEP': raw.SAS_PAIRING_EVENT_CONNECTION_STEP,
  'SAS_PAIRING_EVENT_CONNECTION_CLOSED':
      raw.SAS_PAIRING_EVENT_CONNECTION_CLOSED,
  'SAS_PAIRING_STEP_NONE': raw.SAS_PAIRING_STEP_NONE,
  'SAS_PAIRING_STEP_INBOUND': raw.SAS_PAIRING_STEP_INBOUND,
  'SAS_PAIRING_STEP_REFUSED': raw.SAS_PAIRING_STEP_REFUSED,
  'SAS_PAIRING_STEP_DEADLINE': raw.SAS_PAIRING_STEP_DEADLINE,
  'SAS_PAIRING_STEP_WRITTEN': raw.SAS_PAIRING_STEP_WRITTEN,
  'SAS_PAIRING_STEP_CONFIRMED': raw.SAS_PAIRING_STEP_CONFIRMED,
  'SAS_PAIRING_STEP_UNCONFIRMED': raw.SAS_PAIRING_STEP_UNCONFIRMED,
  'SAS_PAIRING_STEP_DISCARDED': raw.SAS_PAIRING_STEP_DISCARDED,
  'SAS_PAIRING_PROTOCOL_EVENT_NONE': raw.SAS_PAIRING_PROTOCOL_EVENT_NONE,
  'SAS_PAIRING_PROTOCOL_EVENT_START_ACCEPTED':
      raw.SAS_PAIRING_PROTOCOL_EVENT_START_ACCEPTED,
  'SAS_PAIRING_PROTOCOL_EVENT_START_DUPLICATE':
      raw.SAS_PAIRING_PROTOCOL_EVENT_START_DUPLICATE,
  'SAS_PAIRING_PROTOCOL_EVENT_ACCEPT': raw.SAS_PAIRING_PROTOCOL_EVENT_ACCEPT,
  'SAS_PAIRING_PROTOCOL_EVENT_INITIATOR_KEY':
      raw.SAS_PAIRING_PROTOCOL_EVENT_INITIATOR_KEY,
  'SAS_PAIRING_PROTOCOL_EVENT_RESPONDER_KEY':
      raw.SAS_PAIRING_PROTOCOL_EVENT_RESPONDER_KEY,
  'SAS_PAIRING_PROTOCOL_EVENT_BOOTSTRAP_MAC_AUTHENTICATED':
      raw.SAS_PAIRING_PROTOCOL_EVENT_BOOTSTRAP_MAC_AUTHENTICATED,
  'SAS_PAIRING_PROTOCOL_EVENT_BOOTSTRAP_MAC_DUPLICATE':
      raw.SAS_PAIRING_PROTOCOL_EVENT_BOOTSTRAP_MAC_DUPLICATE,
  'SAS_PAIRING_PROTOCOL_EVENT_INITIATOR_FINISH':
      raw.SAS_PAIRING_PROTOCOL_EVENT_INITIATOR_FINISH,
  'SAS_PAIRING_PROTOCOL_EVENT_INITIATOR_FINISH_DUPLICATE':
      raw.SAS_PAIRING_PROTOCOL_EVENT_INITIATOR_FINISH_DUPLICATE,
  'SAS_PAIRING_PROTOCOL_EVENT_RESPONDER_FINISH_ACK':
      raw.SAS_PAIRING_PROTOCOL_EVENT_RESPONDER_FINISH_ACK,
  'SAS_PAIRING_PROTOCOL_EVENT_INITIATOR_FINISH_ACK':
      raw.SAS_PAIRING_PROTOCOL_EVENT_INITIATOR_FINISH_ACK,
  'SAS_PAIRING_PROTOCOL_EVENT_PEER_CANCEL':
      raw.SAS_PAIRING_PROTOCOL_EVENT_PEER_CANCEL,
  'SAS_PAIRING_EVENT_REASON_NONE': raw.SAS_PAIRING_EVENT_REASON_NONE,
  'SAS_PAIRING_EVENT_REASON_RESOURCE_LIMITED':
      raw.SAS_PAIRING_EVENT_REASON_RESOURCE_LIMITED,
  'SAS_PAIRING_EVENT_REASON_PEER_CLOSED':
      raw.SAS_PAIRING_EVENT_REASON_PEER_CLOSED,
  'SAS_PAIRING_EVENT_REASON_SOCKET_IO': raw.SAS_PAIRING_EVENT_REASON_SOCKET_IO,
  'SAS_PAIRING_EVENT_REASON_ABANDONED_PARTIAL_FRAME':
      raw.SAS_PAIRING_EVENT_REASON_ABANDONED_PARTIAL_FRAME,
  'SAS_PAIRING_EVENT_REASON_READINESS_FAILURE':
      raw.SAS_PAIRING_EVENT_REASON_READINESS_FAILURE,
  'SAS_PAIRING_EVENT_REASON_LISTENER_IO':
      raw.SAS_PAIRING_EVENT_REASON_LISTENER_IO,
  'SAS_PAIRING_EVENT_REASON_LISTENER_READINESS':
      raw.SAS_PAIRING_EVENT_REASON_LISTENER_READINESS,
  'SAS_PAIRING_EVENT_REASON_ROUTE_REFUSED':
      raw.SAS_PAIRING_EVENT_REASON_ROUTE_REFUSED,
  'SAS_PAIRING_EVENT_REASON_OWNERSHIP_UNCERTAIN':
      raw.SAS_PAIRING_EVENT_REASON_OWNERSHIP_UNCERTAIN,
  'SAS_PAIRING_EVENT_REASON_OTHER_HOST_FAILURE':
      raw.SAS_PAIRING_EVENT_REASON_OTHER_HOST_FAILURE,
  'SAS_PAIRING_EVENT_REASON_INVALID_FRAME':
      raw.SAS_PAIRING_EVENT_REASON_INVALID_FRAME,
  'SAS_PAIRING_EVENT_REASON_TRANSPORT_DEADLINE':
      raw.SAS_PAIRING_EVENT_REASON_TRANSPORT_DEADLINE,
  'SAS_PAIRING_EVENT_REASON_CLOCK_UNAVAILABLE':
      raw.SAS_PAIRING_EVENT_REASON_CLOCK_UNAVAILABLE,
  'SAS_PAIRING_EVENT_REASON_SESSION_PROTOCOL_FAILURE':
      raw.SAS_PAIRING_EVENT_REASON_SESSION_PROTOCOL_FAILURE,
  'SAS_PAIRING_EVENT_REASON_ALREADY_CLOSED':
      raw.SAS_PAIRING_EVENT_REASON_ALREADY_CLOSED,
  'SAS_PAIRING_DEADLINE_NONE': raw.SAS_PAIRING_DEADLINE_NONE,
  'SAS_PAIRING_DEADLINE_ABSOLUTE_TIMEOUT':
      raw.SAS_PAIRING_DEADLINE_ABSOLUTE_TIMEOUT,
  'SAS_PAIRING_DEADLINE_INACTIVITY_TIMEOUT':
      raw.SAS_PAIRING_DEADLINE_INACTIVITY_TIMEOUT,
  'SAS_PAIRING_DEADLINE_PENDING_EXPIRED':
      raw.SAS_PAIRING_DEADLINE_PENDING_EXPIRED,
  'SAS_PAIRING_DEADLINE_CLOCK_UNAVAILABLE':
      raw.SAS_PAIRING_DEADLINE_CLOCK_UNAVAILABLE,
  'SAS_PAIRING_CANCEL_STATE_NONE': raw.SAS_PAIRING_CANCEL_STATE_NONE,
  'SAS_PAIRING_CANCEL_STATE_NOT_BUILT': raw.SAS_PAIRING_CANCEL_STATE_NOT_BUILT,
  'SAS_PAIRING_CANCEL_STATE_PENDING': raw.SAS_PAIRING_CANCEL_STATE_PENDING,
  'SAS_PAIRING_CANCEL_STATE_DROPPED': raw.SAS_PAIRING_CANCEL_STATE_DROPPED,
  'SAS_PAIRING_CANCEL_REASON_NONE': raw.SAS_PAIRING_CANCEL_REASON_NONE,
  'SAS_PAIRING_CANCEL_REASON_USER_REJECTION':
      raw.SAS_PAIRING_CANCEL_REASON_USER_REJECTION,
  'SAS_PAIRING_CANCEL_REASON_USER_CANCELLATION':
      raw.SAS_PAIRING_CANCEL_REASON_USER_CANCELLATION,
  'SAS_PAIRING_CANCEL_REASON_TIMEOUT': raw.SAS_PAIRING_CANCEL_REASON_TIMEOUT,
  'SAS_PAIRING_CANCEL_REASON_LOCAL_POLICY_FAILURE':
      raw.SAS_PAIRING_CANCEL_REASON_LOCAL_POLICY_FAILURE,
  'SAS_PAIRING_EVENT_FLAG_WRITE_PENDING':
      raw.SAS_PAIRING_EVENT_FLAG_WRITE_PENDING,
  'SAS_PAIRING_EVENT_FLAG_RUN_UNTRACKED':
      raw.SAS_PAIRING_EVENT_FLAG_RUN_UNTRACKED,
  'SAS_PAIRING_ROLE_INVALID': raw.SAS_PAIRING_ROLE_INVALID,
  'SAS_PAIRING_ROLE_INITIATOR': raw.SAS_PAIRING_ROLE_INITIATOR,
  'SAS_PAIRING_ROLE_RESPONDER': raw.SAS_PAIRING_ROLE_RESPONDER,
  'SAS_PAIRING_RESULT_FIELD_REQUEST_ID':
      raw.SAS_PAIRING_RESULT_FIELD_REQUEST_ID,
  'SAS_PAIRING_RESULT_FIELD_AUTHENTICATED_PEER_BOOTSTRAP':
      raw.SAS_PAIRING_RESULT_FIELD_AUTHENTICATED_PEER_BOOTSTRAP,
  'SAS_PAIRING_RESULT_FIELD_AUTHENTICATED_SHARED_CONTEXT':
      raw.SAS_PAIRING_RESULT_FIELD_AUTHENTICATED_SHARED_CONTEXT,
  'SAS_PAIRING_RESULT_FIELD_PROFILE_IDENTIFIER':
      raw.SAS_PAIRING_RESULT_FIELD_PROFILE_IDENTIFIER,
  'SAS_PAIRING_LOCAL_EVENT_INVALID': raw.SAS_PAIRING_LOCAL_EVENT_INVALID,
  'SAS_PAIRING_LOCAL_EVENT_INITIATOR_STARTED':
      raw.SAS_PAIRING_LOCAL_EVENT_INITIATOR_STARTED,
  'SAS_PAIRING_LOCAL_EVENT_EXPOSURE_AUTHORIZED':
      raw.SAS_PAIRING_LOCAL_EVENT_EXPOSURE_AUTHORIZED,
  'SAS_PAIRING_LOCAL_EVENT_KEY_EXPOSED':
      raw.SAS_PAIRING_LOCAL_EVENT_KEY_EXPOSED,
  'SAS_PAIRING_LOCAL_EVENT_SAS_APPROVED':
      raw.SAS_PAIRING_LOCAL_EVENT_SAS_APPROVED,
  'SAS_PAIRING_LOCAL_EVENT_SAS_ALREADY_APPROVED':
      raw.SAS_PAIRING_LOCAL_EVENT_SAS_ALREADY_APPROVED,
  'SAS_PAIRING_LOCAL_EVENT_BOOTSTRAP_MAC_EMITTED':
      raw.SAS_PAIRING_LOCAL_EVENT_BOOTSTRAP_MAC_EMITTED,
  'SAS_PAIRING_LOCAL_EVENT_BOOTSTRAP_MAC_ALREADY_EMITTED':
      raw.SAS_PAIRING_LOCAL_EVENT_BOOTSTRAP_MAC_ALREADY_EMITTED,
  'SAS_PAIRING_LOCAL_EVENT_INITIATOR_FINISH_EMITTED':
      raw.SAS_PAIRING_LOCAL_EVENT_INITIATOR_FINISH_EMITTED,
  'SAS_PAIRING_LOCAL_EVENT_INITIATOR_FINISH_ALREADY_EMITTED':
      raw.SAS_PAIRING_LOCAL_EVENT_INITIATOR_FINISH_ALREADY_EMITTED,
  'SAS_PAIRING_LOCAL_EVENT_SAS_REJECTED':
      raw.SAS_PAIRING_LOCAL_EVENT_SAS_REJECTED,
  'SAS_PAIRING_LOCAL_EVENT_SAS_CANCELLED':
      raw.SAS_PAIRING_LOCAL_EVENT_SAS_CANCELLED,
  'SAS_PAIRING_LOCAL_EVENT_DEADLINE': raw.SAS_PAIRING_LOCAL_EVENT_DEADLINE,
  'SAS_PAIRING_ACTION_FLAG_WRITE_PENDING':
      raw.SAS_PAIRING_ACTION_FLAG_WRITE_PENDING,
};

/// Manifest §5: handle invalid values and scalar constants.
///
/// `SAS_PAIRING_SOCKET_INVALID` is `UINTPTR_MAX`. Dart has no unsigned 64-bit integer, so on the
/// supported 64-bit target its all-ones bit pattern reads as `-1`; written to a `UintPtr` slot it
/// is exactly `UINTPTR_MAX` again.
const Map<String, int> abiV1Scalars = <String, int>{
  'SAS_PAIRING_RUNTIME_INVALID': raw.SAS_PAIRING_RUNTIME_INVALID,
  'SAS_PAIRING_AUTHORITY_INVALID': raw.SAS_PAIRING_AUTHORITY_INVALID,
  'SAS_PAIRING_HOST_INVALID': raw.SAS_PAIRING_HOST_INVALID,
  'SAS_PAIRING_SOCKET_INVALID': raw.SAS_PAIRING_SOCKET_INVALID,
  'SAS_PAIRING_CONNECTION_INVALID': raw.SAS_PAIRING_CONNECTION_INVALID,
  'SAS_PAIRING_RUN_INVALID': raw.SAS_PAIRING_RUN_INVALID,
  'SAS_PAIRING_RESULT_INVALID': raw.SAS_PAIRING_RESULT_INVALID,
  'SAS_PAIRING_MAX_DRIVE_EVENTS': raw.SAS_PAIRING_MAX_DRIVE_EVENTS,
  'SAS_PAIRING_MAX_REQUEST_ID_LEN': raw.SAS_PAIRING_MAX_REQUEST_ID_LEN,
  'SAS_PAIRING_MAX_RUNS_PER_CONNECTION':
      raw.SAS_PAIRING_MAX_RUNS_PER_CONNECTION,
  'SAS_PAIRING_SAS_DECIMAL_LEN': raw.SAS_PAIRING_SAS_DECIMAL_LEN,
};

/// Manifest §7: the frozen 64-bit sizes of the six public records, by C typedef name. Tests
/// compare these with both the manifest and `sizeOf` of the generated records.
const Map<String, int> abiV1RecordSizes = <String, int>{
  'sas_pairing_bytes_view_t': 16,
  'sas_pairing_bootstrap_view_t': 64,
  'sas_pairing_event_t': 128,
  'sas_pairing_result_info_t': 56,
  'sas_pairing_action_t': 24,
  'sas_pairing_sas_presentation_t': 56,
};
